---
# file: roles/ifkstat-resurser/tasks/main.yml


- name: configure shared jdbc datasource for ifkstat
  lineinfile:
    dest="{{ tomcat_conf }}/server.xml"
    regexp="    <Resource name='sharedIfkstat'"
    insertbefore="  </GlobalNamingResources>"
    line="    <Resource name='sharedIfkstat' global='sharedIfkstat'  auth='Container' type='javax.sql.DataSource' username='{{ database_username }}' password='{{ database_password }}' driverClassName='{{ database_driver }}' url='{{ database_url }}' maxActive='{{ database_pool_maxActive }}' maxIdle='{{ database_pool_maxIdle }}' minIdle='{{ database_pool_minIdle }}' initialSize='{{ database_pool_initialSize }}' validationQuery='SELECT 1' validationQueryTimeout='3' testWhileIdle='true' timeBetweenEvictionRunsMillis='300000' minEvictableIdleTimeMillis='60000' defaultAutocommit='false' />"

- name: configure jdbc resource
  lineinfile:
    dest="{{ tomcat_conf }}/context.xml"
    regexp="    <ResourceLink name='jdbc/ifkstat'|    <Resource name='jdbc/ifkstat'"
    insertbefore="</Context>"
    line="    <ResourceLink name='jdbc/ifkstat' global='sharedIfkstat' type='javax.sql.DataSource'/>"