---
# file: roles/oracle-jre8/tasks/main.yml

- name: Create {{ ifkstat_root }} directory
  file: state=directory dest={{ ifkstat_root }} mode=755

- name: Create {{ archive_dir }} directory
  file: state=directory dest={{ archive_dir }} mode=755

- name: Create JAVA_HOME directory
  file: state=directory dest={{ java_home }} mode=755

- name: Download java
  command: "creates={{ archive_dir }}/{{ jre_tarball }} \
           curl http://sdlc-esd.oracle.com/ESD6/JSCDL/jdk/{{ java_version }}/jre-8u60-linux-x64.tar.gz?GroupName=JSC&FilePath=/ESD6/JSCDL/jdk/{{ java_version }}/jre-8u60-linux-x64.tar.gz&BHost=javadl.sun.com&File=jre-8u60-linux-x64.tar.gz&AuthParam=1441485469_47200251893c874a8c0b04984dcc5fe2&ext=.gz -o {{ archive_dir }}/{{ jre_tarball }} -L -H 'Cookie: oraclelicense=accept-securebackup-cookie'"

- name: Extract java
  command: creates={{ java_home }}/bin/java
           tar zxf {{ archive_dir }}/{{ jre_tarball }} -C {{ java_home }} --strip-components 1

- name: set JAVA_HOME variable
  lineinfile:
    dest="/etc/profile"
    regexp="export JAVA_HOME"
    insertafter="EOF"
    line="export JAVA_HOME={{ java_home }}"

- name: Make java link
  file: state=link src="{{ java_home }}/bin/java" path=/usr/bin/java
